# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

before_all do
    ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = "vtnl-kxne-pfhi-eubn"
  end

platform :ios do

  desc "update_display_name"
   lane :update_display_name do 
   update_info_plist(
    plist_path: "./Buildup/Resources/Info.plist",
    xcodeproj: "./Buildup.xcodeproj",
    display_name: ENV['APP_DISPLAY_NAME']
  )
end

  desc “Update App Identifier”
   lane :update_project_settings do
   require 'xcodeproj'
   project_path = '../Buildup.xcodeproj'
   project = Xcodeproj::Project.open(project_path)

  project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['PRODUCT_BUNDLE_IDENTIFIER'] =  ENV['APP_IDENTIFIER']
    end
  end

  project.save

 update_app_identifier(app_identifier: ENV['APP_IDENTIFIER'], plist_path: "BuildUp/Resources/Info.plist")
end

 desc “Update Provisioning”
 profile_name = "AppStore_" + ENV['APP_IDENTIFIER'] + ".mobileprovision"
  lane :update_provisioning do
    update_project_provisioning(
    xcodeproj: './Buildup.xcodeproj',
    profile: profile_name,
    target_filter: '.*',
    build_configuration: 'Release',
   code_signing_identity: 'iPhone Distribution'
  )
end

 desc “Change base url”
  lane:change_main_host do
    path = '../BuildUp/Services/Configuration.swift'
    re = /\s+url =(.*)/
    s = File.read(path)
    s[re, 0] = ' url = "' + ENV['RELEASE_URL'] +"\""
    f = File.new(path, 'w')
    f.write(s)
    f.close

end

 desc “update colors”
  lane:update_colors do
    change_background_color()
    change_splash_background_color()
end

 desc “change background color”
  lane:change_background_color do
    path = '../BuildUp/Base.lproj/LaunchScreen.storyboard'
    re = / key="backgroundColor"(.*)/
    s = File.read(path)
    background = ' key=“backgroundColor” red="' + ENV['RED'] + ’" green="' + ENV['GREEN’] +’" blue="‘ + ENV[‘BLUE’] +’”  alpha=“1" colorSpace="custom" customColorSpace="sRGB"/>'
    s[re, 0] = background
    f = File.new(path, 'w')
    f.write(s)
    f.close
end

desc “change splash background color”
lane:change_splash_background_color do
    path = '../BuildUp/Features/Splash/SplashViewController.xib'
    re = / key="backgroundColor"(.*)/
    s = File.read(path)
    background = ' key=“backgroundColor” red="' + ENV['RED'] + ’" green="' + ENV['GREEN’] +’" blue="‘ + ENV[‘BLUE’] +’”  alpha=“1" colorSpace="custom" customColorSpace="sRGB"/>'
    s[re, 0] = background
    f = File.new(path, 'w')
    f.write(s)
    f.close
end

 desc "Set the build number to a specific value"
  lane :set_build_number do
    increment_build_number(build_number: ENV['APP_BUILD_NUMBER']) # Set a specific build number
  end

desc "Set the version number to a specific value"
  lane :set_version_number do
    increment_version_number(version_number: ENV['APP_VERSION_NUMBER']) # Set version number
  end

  lane:install_provisioning do
   sigh(
    app_identifier: ENV['APP_IDENTIFIER'],  # Your app's bundle identifier
    username: "mohammed.khaled.sobhy@gmail.com" # Your Apple developer account email
  )
 end

 desc “Change base url + screenshots”
  lane:upload_app do
    change_main_host()
    set_build_number()
    # set_version_number()
    update_colors()
    update_display_name()
    api_key = app_store_connect_api_key(
	  key_id: "223H85GN24",
	  issuer_id: "69a6de71-daeb-47e3-e053-5b8c7c11a4d1",  	 
key_content:"-----BEGIN PRIVATE KEY-----\nMIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQghGStYReHnLsS+qBL
hhD7N1mMiIT4kpz2SJIWf/xSU7mgCgYIKoZIzj0DAQehRANCAARaJePeenpjJuj8
rXoq2fqDz62m4DxsS/9iMRonv6iinalgzw6J8HZ+zZ1ld8wpGRHItX9y/XrxIgDP
SdRzkDKl\n-----END PRIVATE KEY-----"
)
    match(api_key: api_key, readonly: false, force_for_new_devices: true)
    update_project_settings()
    install_provisioning()
    update_provisioning()
    deploy()
end

 desc “Update App”
  lane:update_app do
    change_main_host()
    set_build_number()
    update_colors()
    api_key = app_store_connect_api_key(
	  key_id: "223H85GN24",
	  issuer_id: "69a6de71-daeb-47e3-e053-5b8c7c11a4d1",  	 
key_content:"-----BEGIN PRIVATE KEY-----\nMIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQghGStYReHnLsS+qBL
hhD7N1mMiIT4kpz2SJIWf/xSU7mgCgYIKoZIzj0DAQehRANCAARaJePeenpjJuj8
rXoq2fqDz62m4DxsS/9iMRonv6iinalgzw6J8HZ+zZ1ld8wpGRHItX9y/XrxIgDP
SdRzkDKl\n-----END PRIVATE KEY-----"
)
    match(api_key: api_key, readonly: false, force_for_new_devices: true)
    update_project_settings()
    install_provisioning()
    update_provisioning()
    deploy()
end 

 desc "deploy"
  lane :deploy do
    setup_ci
    sync_code_signing(
      type: "appstore",
      app_identifier: ENV['APP_IDENTIFIER'],
      readonly: false
    )
    build_app(scheme: ENV['SCHEME']) 
    app_store_connect_api_key(
	  key_id: "223H85GN24",
	  issuer_id: "69a6de71-daeb-47e3-e053-5b8c7c11a4d1",  	 
key_content:"-----BEGIN PRIVATE KEY-----\nMIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQghGStYReHnLsS+qBL
hhD7N1mMiIT4kpz2SJIWf/xSU7mgCgYIKoZIzj0DAQehRANCAARaJePeenpjJuj8
rXoq2fqDz62m4DxsS/9iMRonv6iinalgzw6J8HZ+zZ1ld8wpGRHItX9y/XrxIgDP
SdRzkDKl\n-----END PRIVATE KEY-----"
)	
	upload_to_app_store(
    		username: "mohammed.khaled.sobhy@gmail.com",
    		app_identifier: ENV['APP_IDENTIFIER'],
    		skip_metadata: true,
    		skip_screenshots: true,
    		submit_for_review: false,
		run_precheck_before_submit: false,
submission_information: {
      add_id_info_limits_tracking: true,
      add_id_info_serves_ads: false,
      add_id_info_tracks_action: true,
      add_id_info_tracks_install: true,
      add_id_info_uses_idfa: true,
      content_rights_has_rights: true,
      content_rights_contains_third_party_content: true,
      export_compliance_platform: 'ios',
      export_compliance_compliance_required: false,
      export_compliance_encryption_updated: false,
      export_compliance_app_type: nil,
      export_compliance_uses_encryption: false,
      export_compliance_is_exempt: false,
      export_compliance_contains_third_party_cryptography: false,
      export_compliance_contains_proprietary_cryptography: false,
      export_compliance_available_on_french_store: false
    }
  )
  end
end
