name: iOS Build

# on:
#   push:
#     branches: [ ci ]
#   pull_request:
#     branches: [ ci ]

on:
  workflow_dispatch:
    inputs:
      match_git_basic_authorization:
        description: 'MATCH_GIT_BASIC_AUTHORIZATION value'
        required: true
      match_password:
        description: 'MATCH_PASSWORD value'
        required: true
      match_username:
        description: 'MATCH_USERNAME value'
        required: true
      app_store_connect_api_key_key_id:
        description: 'APP_STORE_CONNECT_API_KEY_KEY_ID value'
        required: true
      app_store_connect_api_key_issuer_id:
        description: 'APP_STORE_CONNECT_API_KEY_ISSUER_ID value'
        required: true
      app_store_connect_api_key_key:
        description: 'APP_STORE_CONNECT_API_KEY_KEY value'
        required: true

jobs:
  build:
    runs-on: 'macos-latest'
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2' # or the version you need
    - name: Set up xcode
      uses: maxim-lobanov/setup-xcode@v1.6.0
      with:
        xcode-version: 'latest-stable'

    - name: Set .env.default
      run: |
        echo "MATCH_GIT_BASIC_AUTHORIZATION=${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}" >> $GITHUB_ENV
        echo "MATCH_PASSWORD=${{ secrets.MATCH_PASSWORD }}" >> $GITHUB_ENV
        echo "MATCH_USERNAME=${{ secrets.MATCH_USERNAME }}" >> $GITHUB_ENV
        echo "APP_STORE_CONNECT_API_KEY_KEY_ID=${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}" >> $GITHUB_ENV
        echo "APP_STORE_CONNECT_API_KEY_ISSUER_ID=${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}" >> $GITHUB_ENV
        echo "APP_STORE_CONNECT_API_KEY_KEY=${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}" >> $GITHUB_ENV
  
    - name: Install dependencies
      run: |
        gem install bundler
        pod install
        bundle update --full-index

    - name: Execute Fastlane
    #   env:
    #     MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
    #     FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
    #     FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
    #     FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
      run: |
        fastlane deploy
        
