name: iOS Build with secrets

on:
  push:
    branches: [ fake ]
  pull_request:
    branches: [ fake ]
  workflow_dispatch:
    inputs:
      match_git_basic_authorization:
        description: 'MATCH_GIT_BASIC_AUTHORIZATION value'
        required: true
      match_password:
        description: 'MATCH_PASSWORD value'
        required: true
      match_username:
        description: 'MATCH_USERNAME value'
        required: true
      app_store_connect_api_key_key_id:
        description: 'APP_STORE_CONNECT_API_KEY_KEY_ID value'
        required: true
      app_store_connect_api_key_issuer_id:
        description: 'APP_STORE_CONNECT_API_KEY_ISSUER_ID value'
        required: true
      app_store_connect_api_key_key:
        description: 'APP_STORE_CONNECT_API_KEY_KEY value'
        required: true
      fastlane_apple_application_specific_password:
        description: 'FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD value'
        required: true
      app_file:
        description: 'Appfile'
        required: true
      match_file:
        description: 'Matchfile value'
        required: true
      deploy_id:
        description: 'Deploy id'
        required: true

jobs:
  build:
    runs-on: 'macos-latest'
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2' # or the version you need
    - name: Set up xcode
      uses: maxim-lobanov/setup-xcode@v1.6.0
      with:
        xcode-version: 'latest-stable'

    - name: Set .env.default
      run: |
        rm fastlane/.env.default
        echo "MATCH_GIT_BASIC_AUTHORIZATION=${{ github.event.inputs.match_git_basic_authorization  }}" > fastlane/.env.default
        echo "MATCH_PASSWORD=${{ github.event.inputs.match_password  }}" >> fastlane/.env.default
        echo "MATCH_USERNAME=${{ github.event.inputs.match_username  }}" >> fastlane/.env.default
        echo "APP_STORE_CONNECT_API_KEY_KEY_ID=${{ github.event.inputs.app_store_connect_api_key_key_id  }}" >> fastlane/.env.default
        echo "APP_STORE_CONNECT_API_KEY_ISSUER_ID=${{ github.event.inputs.app_store_connect_api_key_issuer_id  }}" >> fastlane/.env.default
        echo "APP_STORE_CONNECT_API_KEY_KEY=${{ github.event.inputs.app_store_connect_api_key_key  }}" >> fastlane/.env.default
        cat fastlane/.env.default
    - name: Set Appfile
      run: |
        rm fastlane/AppFile
        echo "${{ github.event.inputs.app_file}}" > fastlane/AppFile
        cat fastlane/AppFile

    - name: Set Matchfile
      run: |
        rm fastlane/Matchfile
        echo "${{ github.event.inputs.match_file}}" > fastlane/Matchfile
        cat fastlane/Matchfile

    - name: Install dependencies
      run: |
        gem install bundler
        pod install
        bundle update --full-index

    - name: Execute Fastlane
      #   env:
      #     MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      #     FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
      #     FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
      #     FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
      uses: BuildupTeam/github_actions/run-and-capture-error@main
      with:
        command: fastlane deploy
        step-name: Run Fastlane Build Lens
        error-log-path: ${{ github.workspace }}/errors.txt

    - name: Send Failure Notification
      if: failure()
      run: |
        echo "CI/CD pipeline failed. Sending API request..."
        ERROR_MESSAGE=$(<errors.txt)
        PAYLOAD=$(jq -n \
        --arg auth "${{ github.event.inputs.client_app }}" \
        --arg auth "${{ github.event.inputs.deploy_id }}" \
        --arg run_number "${GITHUB_RUN_NUMBER}" \
        --arg deploy_id "${GITHUB_RUN_NUMBER}" \
        --arg msg "$ERROR_MESSAGE" \
        '{authorization: $auth, workflow_run_number: $run_number, error_message: $msg, deploy_id: $deploy_id}')
        curl -X POST -H "Content-Type: application/json" \
          -d "$PAYLOAD" \
          "https://ecommerce.buildupp.co/ci-failure"

    - name: Send Success Notification
      if: success()
      run: |
        echo "CI/CD pipeline failed. Sending API request..."
        ERROR_MESSAGE=$(<errors.txt)
        ERROR_MESSAGE_JSON=$(echo "$ERROR_MESSAGE" | jq -aRs .)
        max_attempts=3
        attempt=1
        sleep_seconds=5
        while [ $attempt -le $max_attempts ]; do
          echo "Attempt $attempt of $max_attempts"
          curl -X POST -H "Content-Type: multipart/form-data" \
               -F "authorization=${{ github.event.inputs.client_app }}" \
               -F "authorization=${{ github.event.inputs.deploy_id }}" \
               -F "workflow_run_number=${GITHUB_RUN_NUMBER}" \
               -F "error_message=$ERROR_MESSAGE_JSON" \
               "https://ecommerce.buildupp.co/ec/api/ci-success" && break
          echo "curl command failed, retrying in $sleep_seconds seconds..."
          sleep $sleep_seconds
          attempt=$(( attempt + 1 ))
        done
        if [ $attempt -gt $max_attempts ]; then
          echo "curl command failed after $max_attempts attempts"
          exit 1
        fi
