name: iOS Build

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

jobs:
  build:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2' # or the version you need
    # - name: Set up xcode
    #   uses: maxim-lobanov/setup-xcode@v1.6.0
    #   with:
    #     xcode-version: '14.2.0'

    - name: Install dependencies
      run: |
        gem install bundler
        pod install
        bundle update --full-index

    - name: Execute Fastlane
    #   env:
    #     MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
    #     FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
    #     FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
    #     FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
      run: |
        fastlane beta
        