name: iOS generate screenshots

on:
  push:
    branches: [ fakeDummyRepo ]
  pull_request:
    branches: [ fakeDummyRepo ]
  workflow_dispatch:
    inputs:
      env_file:
        description: 'Env file'
        required: true
      app_file:
        description: 'Appfile'
        required: true
      match_file:
        description: 'Matchfile value'
        required: true
      deployment_id:
        description: 'Deployment id'
        required: true
      client_app:
        description: 'Client app slug'
        required: true
      aws_access_key_id:
        description: 'AWS_ACCESS_KEY_ID'
        required: true
      aws_secret_access_key:
        description: 'AWS_SECRET_ACCESS_KEY'
        required: true
      success_url:
        description: 'SUCCESS_URL'
        required: true
      failure_url:
        description: 'FAILURE_URL'
        required: true

jobs:
  build:
    runs-on: 'macos-latest'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2' # or the version you need
      - name: Set up xcode
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: 'latest-stable'

      - name: Set .env.default
        run: |
          rm fastlane/.env.default
          echo "${{ github.event.inputs.env_file}}" > fastlane/.env.default
          cat fastlane/.env.default

      - name: display fastlane file
        run: |
          cat fastlane/Fastfile

      - name: Set Appfile
        run: |
          rm fastlane/AppFile
          echo "${{ github.event.inputs.app_file}}" > fastlane/AppFile
          cat fastlane/AppFile

      - name: Set Matchfile
        run: |
          rm fastlane/Matchfile
          echo "${{ github.event.inputs.match_file}}" > fastlane/Matchfile
          cat fastlane/Matchfile

      - name: Set up ImageMagick
        run: brew install imagemagick

      - name: Install dependencies
        run: |
          gem install bundler
          pod install
          bundle update --full-index

      - name: Execute Fastlane
        env:
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASS }}
        run: |
          fastlane update_settings
          fastlane snapshot

      - name: Generate Screenshots Mockups
        env:
          PROJECT_PATH: ${{ github.workspace }}
        run: |
          brew install jq
          chmod +x ./ScreenshotsGenerator/screenshot_generator.sh
          ./ScreenshotsGenerator/screenshot_generator.sh
          zip -jr iosScreenshots.zip ${{ github.workspace }}/ScreenshotsGenerator/screen_output/*

      - name: Set up Python (for AWS CLI)
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install AWS CLI
        run: pip install awscli

      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ github.event.inputs.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ github.event.inputs.aws_secret_access_key }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region us-east-1

      - name: Upload compressed screenshots to S3
        run: aws s3 cp iosScreenshots.zip s3://buildup-staging-uploads/uploads/${{ github.event.inputs.client_app }}/iosScreenshots.zip

      - name: Send Success Notification
        if: success()
        run: |
          echo "CI/CD pipeline failed. Sending API request..."
          max_attempts=3
          attempt=1
          sleep_seconds=5
          while [ $attempt -le $max_attempts ]; do
            echo "Attempt $attempt of $max_attempts"
            curl -X POST -H "Content-Type: multipart/form-data" \
                 -F "authorization=${{ github.event.inputs.client_app }}" \
                 -F "deployment_id=${{ github.event.inputs.deployment_id }}" \
                 -F "workflow_run_number=${GITHUB_RUN_NUMBER}" \
                 -F "screenshots_url=\"https://buildup-staging-uploads.s3.us-east-2.amazonaws.com/uploads/${{ github.event.inputs.client_app }}/iosScreenshots.zip\"" \
                 "${{ github.event.inputs.success_url }}" && break
            echo "curl command failed, retrying in $sleep_seconds seconds..."
            sleep $sleep_seconds
            attempt=$(( attempt + 1 ))
          done
          if [ $attempt -gt $max_attempts ]; then
            echo "curl command failed after $max_attempts attempts"
            exit 1
          fi

      - name: Send Failure Notification
        if: failure()
        run: |
          echo "CI/CD pipeline failed. Sending API request..."
          PAYLOAD=$(jq -n \
          --arg auth "${{ github.event.inputs.client_app }}" \
          --arg deployment_id "${{ github.event.inputs.deployment_id }}" \
          --arg run_number "${GITHUB_RUN_NUMBER}" \
          '{authorization: $auth, workflow_run_number: $run_number, deployment_id: $deployment_id}')
          curl -X POST -H "Content-Type: application/json" \
            -d "$PAYLOAD" \
            "${{ github.event.inputs.failure_url }}"